### ISSUE TITLE
notarized routes are not discarded after every test

### ISSUE THREAD

**Issue by jorgebo10** [bkbnio/kompendium#453] opened 2023-04-25 19:31 UTC
**Describe the bug**
Seems that notarized routes are not being removed after every test.
`java.lang.IllegalArgumentException: A route has already been registered for path: /itineraries/search and method: POST
`

**To Reproduce**

```

fun Route.getAvailabilityRoute(
    getAvailabilityUseCase: UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>>,
    calendar: Calendar,
) {
    route("/itineraries/search") {
        findItinerariesDocumentation()
        post {
            val createdAt = calendar.instant()
            val requestDTO = call.receive<GetAvailabilityRequestDTO>()

            // TODO: Workaround para flybondi seatch/book
            val modifiedDto = requestDTO.copy(
                from = getModifiedIata(requestDTO.from),
                to = getModifiedIata(requestDTO.to)
            )

            parseGetAvailabilityCommand(modifiedDto, createdAt)
                .flatMap { getAvailabilityUseCase(it) }
                .fold({ handleLeft(it) }) {
                    val dto = parseGetAvailabilityResponseDTO(it.first.toItineraryDTOList(createdAt))
                    handleRight(dto)
                }
        }
    }
}

private fun Route.findItinerariesDocumentation() {
    install(NotarizedRoute()) {
        post = PostInfo.builder {
            description("Availability search")
            summary("Search for itinerary availability.")
            request {
                description("Search for itineraries which are available according to the search parameters.")
                requestType(typeOf<GetAvailabilityRequestDTO>())
            }
            response {
                responseCode(HttpStatusCode.OK)
                responseType(typeOf<GetAvailabilityResponseDTO>())
                description("Itineraries found")
                examples("itineraries" to GetAvailabilityResponseDTO(emptyList()))
            }
            canRespond {
                description("Client can make mistakes too")
                responseCode(HttpStatusCode.BadRequest)
                responseType(typeOf<ProblemDetail>())
                examples(
                    "Market not available" to ProblemDetail(
                        type = URI.create("https://httpstatuses.com/400").toString(),
                        title = "Market not available",
                        detail = "Market BUE not available",
                        statusCode = HttpStatusCode.BadRequest.value,
                        instance = "/itineraries/search",
                    )
                )
            }
            canRespond {
                description("Bad things can happend")
                responseCode(HttpStatusCode.InternalServerError)
                responseType(typeOf<ProblemDetail>())
                examples(
                    "Server problem" to ProblemDetail(
                        type = URI.create("https://httpstatuses.com/500").toString(),
                        title = HttpStatusCode.InternalServerError.description,
                        statusCode = HttpStatusCode.InternalServerError.value,
                        instance = "/itineraries/search",
                    )
                )
            }
        }
    }
}

fun Application.registerGetAvailabilityRoute(
    getAvailabilityUseCase: UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>>,
    calendar: Calendar,
) {
    routing {
        getAvailabilityRoute(getAvailabilityUseCase, calendar)
    }
}
```

```
class GetAvailabilityRouteTest {
  

    @Test
    fun `can get 200 with no results`() = testApplication {
        environment {
            config = ApplicationConfig("application-test.conf")
        }
        fun noAvailabilityFoundStub(): UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>> =
            object : UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>> {
                override suspend fun invoke(command: Command<SearchQuery>): Either<BusinessError, Pair<List<Itinerary>, String>> {
                    return Either.Right(emptyList<Itinerary>() to "session")
                }
            }
        application {
            installServerContentNegotiation()
            installIgnoreTrailingSlash()
            installKompendium()
            installExceptionHandler()
            registerHealthRoutes()
            registerOASRoutes()
            routing {
                getAvailabilityRoute(
                    noAvailabilityFoundStub(),
                    TestCalendar
                )
            }
        }

        val response = client.post("/itineraries/search") {
            header(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            header(HttpHeaders.Accept, ContentType.Application.Json.toString())
            setBody(
                """{
                "from": "AEP",
                "to": "BRC",
                "departure": "2022-10-10",
                "arrival": "2022-10-10",
                "passengers": { "adt" : 1, "chd" : 1}
                }"""
            )
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertEquals("""{"itineraries":[]}""", response.bodyAsText())
    }

    @Test
    fun `can get 400 when iata is not 3 chars length`() = testApplication {
        environment {
            config = ApplicationConfig("application-test.conf")
        }
        fun noNeedToCallStub(): UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>> =
            object : UseCase<SearchQuery, BusinessError, Pair<List<Itinerary>, String>> {
                override suspend fun invoke(command: Command<SearchQuery>): Either<BusinessError, Pair<List<Itinerary>, String>> {
                    throw java.lang.IllegalStateException("No need to call me")
                }
            }
        application {
            installServerContentNegotiation()
            installIgnoreTrailingSlash()
            installKompendium()
            installExceptionHandler()
            registerHealthRoutes()
            registerOASRoutes()
            routing {
                getAvailabilityRoute(
                    noNeedToCallStub(),
                    TestCalendar
                )
            }
        }

        val response = client.post("/itineraries/search") {
            header(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            header(HttpHeaders.Accept, ContentType.Application.Json.toString())
            setBody(
                """{
                "from": "MD",
                "to": "BRC",
                "departure": "2022-10-10",
                "arrival": "2022-10-10",
                "passengers": { "adt" : 1, "chd" : 1}
                }"""
            )
        }

        assertEquals(HttpStatusCode.BadRequest, response.status)
        assertEquals(
            """{"type":"https://httpstatuses.com/400","title":"Bad Request","detail":"Invalid iata code value: MD","statusCode":400,"instance":"/itineraries/search"}""",
            response.bodyAsText()
        )
    }
}
```

**Expected behavior**
 Every test pass as expected. After every test notarizedroutes are being removed so that we can initialize them again.

**Additional context**
Ktor 2.3.0
Kompendium latest

**Comment by unredundant** [comment] 2023-04-25 19:46
Fairly confident that this is not a bug in kompendium.  

If I had to guess, you are reusing the testApplication across tests, and attaching different routes, which won't work because the route definitions are ultimately passed back up to the parent application.  

If you want to reference how the kompendium test suite works, each test is bootstrapped via this helper method https://github.com/bkbnio/kompendium/blob/main/core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestHelpers.kt#L98

**Comment by jorgebo10** [comment] 2023-04-25 20:50
I'm attaching only one route . I thought that every testApplication {} reinitialized routes in every call to it. I'm pretty new to Ktor by the way. I'll have a look at that helper method. Thanks for having a look at it.

**Comment by unredundant** [comment] 2023-04-26 13:05
Interesting... I wonder if I ran into the same thing at some point, because I also provide the spec thru a function 

https://github.com/bkbnio/kompendium/blob/main/core/src/testFixtures/kotlin/io/bkbn/kompendium/core/fixtures/TestSpecs.kt

Seems unfortunate that some amount of state persists across separate calls to the testApplication function... wonder if the ktor team is aware of this. 

Anyway, glad you figured out the issue :)

**Comment by unredundant** [comment] 2023-04-26 13:29
Ya know... this actually is an issue w/ Kompendium :facepalm: because the `OpenApiSpec` data class is mutable... changes will persist across application instances.

We should actually make this not the case, though doing so would probably require breaking changes to the library, so it wouldn't land until a major version bump.  Going to reopen this to at least track the issue.  

Thanks for surfacing this

**Comment by unredundant** [comment] 2023-04-26 13:30
It's not really something that people will face in production, but definitely worth cleaning up at some point to make testing more straight forward

**Comment by arthurv89** [comment] 2023-06-20 10:34
I'm also experiencing this issue. Is there a workaround for it?

**Comment by unredundant** [comment] 2023-06-20 12:20
yea reference the way kompendium sets up tests above... basically you need to provide the openapi spec via a function, otherwise operations will mutate that instance, and the instance will then leak incorrect details to subsequent tests.

**Comment by unredundant** [comment] 2023-09-04 01:25
will be fixed in v4... kompendium config will take in a function `() -> OpenApiSpec` instead of just `OpenApiSpec`

**Closed** 2023-09-04 04:22 UTC
